### PR TITLE
Social Scaffold | Milestone3

### PR DESCRIPTION
**Pull request by uzairali19**
In this branch, the users are able to send and receive friend requests from each other. They can choose to accept or delete the request and if they do accept the request they would be mutuals with each other in the Friendship table.

### CODE REVIEW

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @uzairali19, I am Elias, your reviewer for this PR

Well done so far with your project!

I am unable to see the file changes that you did in this pull request so I wont be able to comment on your code.

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [x] When I try to see another users profile or mine, I get this [error](https://prnt.sc/1r5wagu), being unable to send/receive friendships, please fix it.
- [x] I had to remove your Bulma import because it was not finding the dependency, take a look into that.
- [x] When friendship is confirmed, an additional row with reversed user-friend pair is created (I can't see any logic added in your friendship model to handle this, only in the user one, but I am unable to test it because of the crash error)
- [ ] Thanks to this, we can find user friends only by user_id in friendships table (In your user model you are missing to handled confirmed friendships and a has many friends through confirmed friendships)
- [x] User#pending_friends (You are missing to handle pending requests in your user model).
- [x] User posts are being duplicated, please take a look into that.
- [x] UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)) (Right now it is crashing when trying to check this page, please fix it in order to fully test this milestone).
- [x] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))(They are being displayed but duplicated at the moment).
- [x] Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by uzairali19** [comment]
> # Status: Changes Required ♻️
> _Check the comments under the review_
> 
> Hello @uzairali19, I am Elias, your reviewer for this PR
> 
> Well done so far with your project!
> 
> I am unable to see the file changes that you did in this pull request so I wont be able to comment on your code.
> 
> I will mention to you a small summary of things that need to be changed in order to keep moving:
> 
> * [x]  When I try to see another users profile or mine, I get this [error](https://prnt.sc/1r5wagu), being unable to send/receive friendships, please fix it.
> * [ ]  I had to remove your Bulma import because it was not finding the dependency, take a look into that.
> * [x]  When friendship is confirmed, an additional row with reversed user-friend pair is created (I can't see any logic added in your friendship model to handle this, only in the user one, but I am unable to test it because of the crash error)
> * [ ]  Thanks to this, we can find user friends only by user_id in friendships table (In your user model you are missing to handled confirmed friendships and a has many friends through confirmed friendships)
> * [x]  User#pending_friends (You are missing to handle pending requests in your user model).
> * [x]  User posts are being duplicated, please take a look into that.
> * [x]  UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)) (Right now it is crashing when trying to check this page, please fix it in order to fully test this milestone).
> * [x]  PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))(They are being displayed but duplicated at the moment).
> * [x]  Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> Please correct those issues and send another review request, good luck, and well done so far!
> 
> Code review by Elias Castañeda
> 
> _(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Hello Elias, 

Thank you for your brief reply to my project. I have fixed almost everything. You don't have to remove the Bulma import. That is because I have used Bulma classes to custom style the project to match my taste. The dependency it uses is in my Gemfile as `gem 'bulma-rails', '~> 0.9.1'` just do a `bundle install` and you should be good to go. You can find more information about the gem [here](https://rubygems.org/gems/bulma-rails).
Apart from that thank you for pointing out that error. That was due to the incorrect use of the `current_user` helper from the devise I am using for this project. I have fixed it and you should be now able to see the changes on the app.

Thanks,
Uzair Ali

**Review by mke2111 — CHANGES_REQUESTED** [review]
### Hey @uzairali19, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️ As Previously Requested

- [x] Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from Pathwright)
- [x] I followed all instructions in the readme file but I couldn't get the server running successfully. I had to remove your Bulma import because it was not finding the dependency, take a look into that. 
- Add all the necessary steps to follow to run your app successfully.
Screenshot from 2021-09-05 01-42-09

- [x] I get the following error when I log out an existing user that has just been created. For this reason, I could not proceed with the review any further. Give this a fix.
Screenshot from 2021-09-05 01-49-36




> NOTE
> Next reviewer should look into the implemented friendship feature and ensure it works just fine as requested in the first review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
Reviewed by: Roy Mukuye

**Comment by uzairali19** [comment]
> ### Hey @uzairali19,
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> ## Required Changes ♻️ As Previously Requested
> * [x]  Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from Pathwright)
> * [x]  I followed all instructions in the readme file but I couldn't get the server running successfully. I had to remove your Bulma import because it was not finding the dependency, take a look into that.
> * Add all the necessary steps to follow to run your app successfully.
>   Screenshot from 2021-09-05 01-42-09
> * [x]  I get the following error when I log out an existing user that has just been created. For this reason, I could not proceed with the review any further. Give this a fix.
>   Screenshot from 2021-09-05 01-49-36
> 
> > NOTE
> > Next reviewer should look into the implemented friendship feature and ensure it works just fine as requested in the first review.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> Reviewed by: Roy Mukuye

Hello Roy,

I hope this answers your concerns.

https://www.loom.com/share/7d9e5856d1f047bc82d318b0341106e3

Thanks,
Uzair

**Comment by eliasecasta** [comment]
> > # Status: Changes Required ♻️
> > _Check the comments under the review_
> > Hello @uzairali19, I am Elias, your reviewer for this PR
> > Well done so far with your project!
> > I am unable to see the file changes that you did in this pull request so I wont be able to comment on your code.
> > I will mention to you a small summary of things that need to be changed in order to keep moving:
> > 
> > * [x]   When I try to see another users profile or mine, I get this [error](https://prnt.sc/1r5wagu), being unable to send/receive friendships, please fix it.
> > * [ ]   I had to remove your Bulma import because it was not finding the dependency, take a look into that.
> > * [x]   When friendship is confirmed, an additional row with reversed user-friend pair is created (I can't see any logic added in your friendship model to handle this, only in the user one, but I am unable to test it because of the crash error)
> > * [ ]   Thanks to this, we can find user friends only by user_id in friendships table (In your user model you are missing to handle confirmed friendships and a has many friends through confirmed friendships)
> > * [x]   User#pending_friends (You are missing to handle pending requests in your user model).
> > * [x]   User posts are being duplicated, please take a look into that.
> > * [x]   UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)) (Right now it is crashing when trying to check this page, please fix it in order to fully test this milestone).
> > * [x]   PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))(They are being displayed but duplicated at the moment).
> > * [x]   Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> > 
> > Please correct those issues and send another review request, good luck, and well done so far!
> > Code review by Elias Castañeda
> > _(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> Hello Elias,
> 
> Thank you for your brief reply to my project. I have fixed almost everything. You don't have to remove the Bulma import. That is because I have used Bulma classes to custom style the project to match my taste. The dependency it uses is in my Gemfile as `gem 'bulma-rails', '~> 0.9.1'` just do a `bundle install` and you should be good to go. You can find more information about the gem [here](https://rubygems.org/gems/bulma-rails).
> Apart from that thank you for pointing out that error. That was due to the incorrect use of the `current_user` helper from the devise I am using for this project. I have fixed it and you should be now able to see the changes on the app.
> 
> Thanks,
> Uzair Ali

Hello Uzair, 

I understand that and basically disabled your CSS for this project with Bulma, the thing is that the project is not running without that import showing an error. We have to run bundle install for sure to set up all the gems but that one is giving issues, I tried removing the manual version that you have and letting it update to the newest one without luck too.

I would recommend you to run your project in a clean environment like Gitpod (VS Code online basically) and try to debug why is your project not running in another environment that is not yours.

Good luck and let me know if you have any doubt.

**Comment by uzairali19** [comment]
> > > # Status: Changes Required ♻️
> > > _Check the comments under the review_
> > > Hello @uzairali19, I am Elias, your reviewer for this PR
> > > Well done so far with your project!
> > > I am unable to see the file changes that you did in this pull request so I wont be able to comment on your code.
> > > I will mention to you a small summary of things that need to be changed in order to keep moving:
> > > 
> > > * [x]    When I try to see another users profile or mine, I get this [error](https://prnt.sc/1r5wagu), being unable to send/receive friendships, please fix it.
> > > * [x]    I had to remove your Bulma import because it was not finding the dependency, take a look into that.
> > > * [x]    When friendship is confirmed, an additional row with reversed user-friend pair is created (I can't see any logic added in your friendship model to handle this, only in the user one, but I am unable to test it because of the crash error)
> > > * [ ]    Thanks to this, we can find user friends only by user_id in friendships table (In your user model you are missing to handle confirmed friendships and a has many friends through confirmed friendships)
> > > * [x]    User#pending_friends (You are missing to handle pending requests in your user model).
> > > * [x]    User posts are being duplicated, please take a look into that.
> > > * [x]    UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project)) (Right now it is crashing when trying to check this page, please fix it in order to fully test this milestone).
> > > * [x]    PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))(They are being displayed but duplicated at the moment).
> > > * [x]    Unit and integration tests are necessary for this project and milestone, please add them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> > > 
> > > Please correct those issues and send another review request, good luck, and well done so far!
> > > Code review by Elias Castañeda
> > > _(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_
> > > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > 
> > 
> > Hello Elias,
> > Thank you for your brief reply to my project. I have fixed almost everything. You don't have to remove the Bulma import. That is because I have used Bulma classes to custom style the project to match my taste. The dependency it uses is in my Gemfile as `gem 'bulma-rails', '~> 0.9.1'` just do a `bundle install` and you should be good to go. You can find more information about the gem [here](https://rubygems.org/gems/bulma-rails).
> > Apart from that thank you for pointing out that error. That was due to the incorrect use of the `current_user` helper from the devise I am using for this project. I have fixed it and you should be now able to see the changes on the app.
> > Thanks,
> > Uzair Ali
> 
> Hello Uzair,
> 
> I understand that and basically disabled your CSS for this project with Bulma, the thing is that the project is not running without that import showing an error. We have to run bundle install for sure to set up all the gems but that one is giving issues, I tried removing the manual version that you have and letting it update to the newest one without luck too.
> 
> I would recommend you to run your project in a clean environment like Gitpod (VS Code online basically) and try to debug why is your project not running in another environment that is not yours.
> 
> Good luck and let me know if you have any doubt.

Hey @e71az,

Thank you for your feedback. I have created an online deployment for you on Heroku. Please visit [Heroku](https://ror-social-scaffold-uzair.herokuapp.com/users/sign_in) to test the site for yourself. I hope there are no more errors from my end.

Thanks,
Uzair Ali

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
@uzairali19 well-done for implementing the suggested changes by the precious Code Reviewer,I commend your effort,however few changes are required to get your project approved 
### Highlights
I can easily Sign in and Sign out without error 👍🏻 

### To Improve
* [x] UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
* [x] PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
* [ ] Kindly added Unit and Integration tests!** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### once specific changes are made kindly request for another review

**Comment by uzairali19** [comment]
> # STATUS: CHANGES REQUIRED ♻️
> @uzairali19 well-done for implementing the suggested changes by the precious Code Reviewer,I commend your effort,however few changes are required to get your project approved
> 
> ### Highlights
> I can easily Sign in and Sign out without error 👍🏻
> 
> ### To Improve
> * [x]  UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
> * [x]  PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
> * [ ]  Kindly added Unit and Integration tests!** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
> 
> ### once specific changes are made kindly request for another review

Hello taiwo2,

I am sorry but I am very confused. I wanted a better response this time I really did everything the previous reviewers asked me to.

> * [x]  UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
> * [x]  PostsController#index displays posts in a timeline (their own posts + posts from their friends) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

Both of these tasks are well working. You can watch them here:

https://www.loom.com/share/50e29fc49bf04887afcbeba237c8fc14

As for the third part I am working on it. But please, my posts#index page that is the timeline and my users#index page both are having what you are asking me to have on them.

Thanks,
Uzair

**Review by carlos-ssh — APPROVED** [review]
Hi @uzairali19 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mke2111** [comment]
### Hey @uzairali19, 

**This is a great project you have going on, well-done lad**. 
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️

- [ ] Open a new PR for the final milestone(deploy) for your project.
- [ ] Add the Live link to the deployed version of your app to the readme file.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
